language: node_js
node_js:
  - "6"
dist: trusty

# SauceLabs addon for Cross Browser testing
addons:
  sauce_connect: true

# Create .netrc for private repo install
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

before_script:
- npm install -g bower web-component-tester
# pipe bower install output through tee to create a log to parse for errors and preserve exit code
- bower install --force-latest 2>&1 | tee bower-debug.log; ( exit ${PIPESTATUS[0]} )

script:
# pipe wct output through tee to create a log to parse for errors and preserve exit code
- xvfb-run wct --skip-plugin local 2>&1 | tee wct.log; ( exit ${PIPESTATUS[0]} )
