addons:
  sauce_connect: true
branches:
  only:
    - master
cache:
  directories: null
dist: trusty
language: node_js
node_js:
  - '8'
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    template:
      - '%{result}: %{repository} <%{build_url}|#%{build_number}>  (<%{compare_url}|%{commit}>)'
      - "\tin %{duration} for %{author}'s commit:"
      - "\t\"%{commit_subject}\""
    rooms:
      - 'ldschurch:S4NvL7BI3BFGOMfoiSCfARk5#treeweb-gold-builds'
    on_pull_requests: false
    on_success: always
    on_failure: change
    on_start: never
before_install:
  - echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" >> ~/.netrc
  - npm install -g bower
install: npm install
before_script: node_modules/fs-common-build-scripts/bin/before_script.sh
script: 'npm run standard && npx wct --module-resolution=node --npm --configFile wct.conf.windows.json --skip-plugin local && npx wct --configFile wct.conf.json --skip-plugin local 2>&1 | tee wct.log; ( exit ${PIPESTATUS[0]} )'
after_success:
  - node node_modules/fs-common-build-scripts/bin/create_release.js
after_failure:
  - node_modules/fs-common-build-scripts/bin/report_failure_details.sh
after_script:
  - node_modules/fs-common-build-scripts/bin/after_script.sh

